---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: consumer-stats
  namespace: tg-step-counter-dev

  labels:
    app: tg-step-counter
    component: consumer-stats
  annotations:
      keel.sh/policy: major
      keel.sh/trigger: poll
      keel.sh/pollSchedule: "@every 15m"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-step-counter
      component: consumer-stats

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: tg-step-counter
        component: consumer-stats
    spec:
      containers:
        - name: stats
          image: agrrh/tg-step-counter:0.3.2

          env:
            - name: TZ
              value: "Europe/Moscow"

            - name: APP_DEV_MODE
              value: ""

            - name: APP_LANG
              value: "ru"

            - name: APP_NATS_ADDRESS
              value: "nats://nats.tg-step-counter-dev.svc:4222"

            - name: APP_NATS_SUBJECT
              value: "stats.>"

            - name: APP_TG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config
                  key: tg_token

            - name: APP_GOOGLE_SA_PATH
              value: ./config/google-service-account.json

            - name: APP_GOOGLE_SHEET_URI
              valueFrom:
                secretKeyRef:
                  name: config
                  key: google_sheet_uri

          # command: [""]
          args: ["app_consumer_stats.py"]

          volumeMounts:
            - name: google-sa
              mountPath: "/opt/app/config"
              readOnly: true

      volumes:
        - name: google-sa
          secret:
            secretName: config
            items:
              - key: google_sheet_sa_credentials
                path: google-service-account.json
