---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: logic
  namespace: tg-step-counter-prod

  labels:
    app: tg-step-counter
    component: logic

spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-step-counter
      component: logic

  template:
    metadata:
      labels:
        app: tg-step-counter
        component: logic
    spec:
      containers:
        - name: logic
          image: agrrh/tg-step-counter:0.5.10

          env:
            - name: TZ
              value: "Europe/Moscow"

            - name: APP_DEV_MODE
              value: ""

            - name: APP_LANG
              value: "ru"

            - name: APP_NATS_ADDRESS
              value: "nats://nats.bus.svc:4222"

            - name: APP_NATS_SUBJECT
              value: "tg-step-counter.logic.>"

            - name: APP_NATS_SUBJECT_RESPONSE
              value: "tg-step-counter.response"

            - name: APP_TG_TOKEN
              valueFrom:
                secretKeyRef:
                  name: config
                  key: tg_token

            - name: APP_GOOGLE_SA_PATH
              value: ./config/google-service-account.json

            - name: APP_GOOGLE_SHEET_URI
              valueFrom:
                secretKeyRef:
                  name: config
                  key: google_sheet_uri

          # command: [""]
          args: ["app_logic.py"]

          volumeMounts:
            - name: google-sa
              mountPath: "/opt/app/config"
              readOnly: true

      volumes:
        - name: google-sa
          secret:
            secretName: config
            items:
              - key: google_sheet_sa_credentials
                path: google-service-account.json
