---

apiVersion: v1
kind: Service

metadata:
  name: redis
  namespace: tg-step-counter-dev

spec:
  selector:
    app: tg-step-counter
    component: redis

  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
